### ISSUE TITLE
Unable to load space model

### ISSUE THREAD

**Issue by reckart** [zesch/pydkpro#13] opened 2020-02-02 13:36 UTC
When trying to run the examples notebook, I get this error:

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-10-f26cb6887958> in <module>
----> 1 for token in To_spacy(cas)():
      2     print(token.text, token.tag_)

~/git/pydkpro/pydkpro/external.py in __call__(self)
     11 
     12     def __call__(self):
---> 13         nlp = spacy.load("en_core_web_sm")
     14         text = 'Backgammon is one of the oldest known board games.'
     15         doc = nlp(text)

~/git/pydkpro/venv/lib/python3.7/site-packages/spacy/__init__.py in load(name, **overrides)
     28     if depr_path not in (True, False, None):
     29         deprecation_warning(Warnings.W001.format(path=depr_path))
---> 30     return util.load_model(name, **overrides)
     31 
     32 

~/git/pydkpro/venv/lib/python3.7/site-packages/spacy/util.py in load_model(name, **overrides)
    167     elif hasattr(name, "exists"):  # Path or Path-like to model data
    168         return load_model_from_path(name, **overrides)
--> 169     raise IOError(Errors.E050.format(name=name))
    170 
    171 

OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
```

**Comment by aggarwalpiush** [comment] 2020-02-03 01:19
Kindly run the following command in your terminal and rerun the jupyter notebook.

``` python -m spacy download en_core_web_sm```

More explicit installation instructions including this one will be added to README soon.

**Comment by aggarwalpiush** [comment] 2020-02-03 23:58
Instructions are added to readme and to the notebook. Kindly close this issue, if the issue is resolved from your side.

**Closed** 2020-02-21 10:55 UTC
